FROM ubuntu:eoan

RUN apt update \
&& apt -y upgrade \
&& apt-get -y install tesseract-ocr=4.1.0 tesseract-ocr-eng tesseract-ocr-jpn tesseract-ocr-jpn-vert tesseract-ocr-osd \
&& apt-get -y install nodejs \
&& apt -y autoremove 


